apiVersion: sbsh/v1beta1
kind: TerminalProfile
metadata:
  name: k8s-default
spec:
  runTarget: local
  restartPolicy: restart-on-error
  shell:
    cwd: "~/projects"
    cmd: /bin/bash
    cmdArgs: []
    env:
      KUBECONF: "$HOME/.kube/config"
      KUBE_CONTEXT: default
      KUBE_NAMESPACE: default
      HISTSIZE: "5000"
    prompt: '"\[\e[1;31m\]sbsh($SBSH_TERM_PROFILE/$SBSH_TERM_ID) \[\e[1;32m\]\u@\h\[\e[0m\]:\w\$ "'
  stages:
    onInit:
      - script: kubectl config use-context $KUBE_CONTEXT
      - script: kubectl config get-contexts
    postAttach:
      - script: kubectl get ns
      - script: kubectl -n $KUBE_NAMESPACE get pods
