apiVersion: sbsh/v1beta1
kind: SessionProfile
metadata:
  name: default
spec:
  runTarget: local
  restartPolicy: restart-on-error
  shell:
    cwd: "~"
    cmd: /bin/bash
    cmdArgs: ["--norc", "--noprofile"]
    inheritEnv: false
    env:
      LANG: en_US.UTF-8
      EDITOR: vim
      HISTSIZE: "5000"
    prompt: "\"[sbsh-$SBSH_SES_ID] \\u@\\h:\\w$ \""
  stages:
    onInit:
      - script: ls -l $TEST
        env:
          TEST: "/tmp"
      - script: sleep 1
    postAttach:
      - script: echo "attached"
---
apiVersion: sbsh/v1beta1
kind: SessionProfile
metadata:
  name: prod
spec:
  runTarget: local
  restartPolicy: restart-on-error
  shell:
    cwd: "~/projects"
    cmd: /bin/bash
    cmdArgs: []
    env:
      KUBE_CONFIG: "$HOME/.kube/config"
      KUBE_CONTEXT: company-prd
      KUBE_NAMESPACE: prd
      JAPON: pepe
      POD: app
      HISTSIZE: "5000"
    prompt: '"\[\e[1;31m\][PRD] sbsh-$SBSH_SES_ID\[\e[0m\] \[\e[1;33m\]\u@\h\[\e[0m\]:\w\$ "'
  stages:
    onInit:
      - script: kubectl -n $KUBE_NAMESPACE describe pod $POD
      - script: bash -c 'echo -e $VAR'
        env:
          VAR: "Hello World"
    postAttach:
      - script: echo "attached"
---
apiVersion: sbsh/v1beta1
kind: SessionProfile
metadata:
  name: work-tf-prd-plan
spec:
  runTarget: local
  restartPolicy: exit
  shell:
    cwd: "~/project/terraform"
    cmd: /bin/bash
    cmdArgs: []
    env:
      HISTSIZE: "5000"
      TF_VAR_environment: "prd"
    prompt: '"[sbsh-$SBSH_SES_ID][PRD]\u@\h:\w$ "'
  stages:
    onInit:
      - script: terraform workspace use $TF_VAR_environment
      - script: terraform init
---
apiVersion: sbsh/v1beta1
kind: SessionProfile
metadata:
  name: work-tf-prd-apply
spec:
  runTarget: local
  restartPolicy: exit
  shell:
    cwd: "~"
    cmd: /bin/bash
    cmdArgs: []
    env:
      HISTSIZE: "5000"
      TF_VAR_environment: "prd"
    prompt: '"[sbsh-$SBSH_SES_ID][PRD]\u@\h:\w$ "'
  stages:
    onInit:
      - script: terraform workspace use $TF_VAR_environment
      - script: terraform init
      - script: terraform plan -out=tfplan
      - script: terraform apply tfplan
---
apiVersion: sbsh/v1beta1
kind: SessionProfile
metadata:
  name: diag-pod-prd
spec:
  runTarget: local
  restartPolicy: exit
  shell:
    cwd: "~"
    cmd: /bin/kubectl
    cmdArgs: ["-n prd run -ti --rm --image debian:latest diag-pod"]
    env:
      KUBECONFIG: "~/.kube/config"
      KUBE_CONTEXT: "prd"
---
apiVersion: sbsh/v1beta1
kind: SessionProfile
metadata:
  name: diag-docker
spec:
  runTarget: local
  restartPolicy: exit
  shell:
    cwd: "~"
    cmd: /usr/bin/docker
    cmdArgs: ["run", "--rm", "-ti", "debian:latest", "/bin/bash"]
    env:
      KUBECONFIG: "~/.kube/config"
      KUBE_CONTEXT: "prd"
