apiVersion: sbsh/v1beta1
kind: TerminalProfile
metadata:
  name: mongo
spec:
  runTarget: local
  restartPolicy: exit
  shell:
    cwd: "~"
    cmd: /usr/bin/mongosh
    cmdArgs:
      - "${MONGO_URI:-mongodb://localhost:27017}"
    setPrompt: false
    env:
      MONGO_URI: "mongodb://localhost:27017"
      MONGO_HOST: "localhost"
      MONGO_PORT: "27017"
      MONGO_DATABASE: "test"
      MONGO_USER: ""
      MONGO_PASSWORD: ""
